name: Deploy SQL to S3 and Run Glue

on:
  push:
    branches: [ "main" ]
    paths:
      - "sql/**"
      - "glue/**"
      - ".github/workflows/**"
  workflow_dispatch:

jobs:
  deploy-and-run:
    runs-on: ubuntu-latest

    permissions:
      id-token: write   # for OIDC
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # --- Recommended: OIDC auth to AWS (no access keys stored)
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::765017559809:role/GitHubActionsDay11SqlDeployRole
          aws-region: us-east-1

      - name: Sync SQL to S3
        run: |
          aws s3 sync day-12-13/sql s3://day11-12-sql-glue/sql --delete

 
      - name: Upload Glue script to S3
        run: |
          aws s3 cp day-12-13/glue/run-athena-glue.py s3://day11-12-sql-glue/glue/run-athena-glue.py


      - name: Start Glue Job
        run: |
          aws glue start-job-run --job-name day11-12-athena-sql-runner
